### ISSUE TITLE
Installation required manual dependency management

### ISSUE THREAD

**Issue by Halmela** [kdwk/Spidey#69]
I downloaded the latest nightly-flatpak from the link in README and tried to install it:
```
$ flatpak install --user spidey.flatpak
error: The application com.github.kdwk.Spidey.Devel/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
```

Then I tried to install the master-branch:
```
$ flatpak install --user org.gnome.Platform/x86_64/master
Looking for matches…
error: No remote refs found similar to ‘org.gnome.Platform/x86_64/master’
```
Default flatpak repository holds only version numbered releases of Platform, so I added gnome-nightly remote:
```flatpak remote-add --user gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo```
and it fixed the installation.

Is this the intended way of installation?

**Comment by kdwk** [comment]
Yes, that's intended. The Developer version requires the master platform from Gnome Nightly because to provide the latest versions of WebKitGTK and other technologies. 

I'll update README to include instructions to add the Gnome Nightly repository. Thanks for pointing this out.
